#colorscheme
import = ["~/.config/alacritty/nord.toml"]

[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 10, y = 10}

[font]
normal = {family = "JetBrainsMonoNL Nerd Font", style = "Regular"}
bold = {family = "JetBrainsMonoNL Nerd Font", style = "Bold"}
italic = {family = "JetBrainsMonoNL Nerd Font", style = "Italic"}
bold_italic = {family = "JetBrainsMonoNL Nerd Font", style = "Bold_italic"}
size = 10
offset = { x = 0, y = 0}
glyph_offset  = { x = -1 , y = 0}
builtin_box_drawing = true
