# --- Main Colors ---
background            #131318
foreground            #e4e1e9
cursor                #e4e1e9
cursor_text_color     #131318

selection_background  #454559
selection_foreground  #e2e0f9

url_color             #e9b9d3

# --- ANSI Colors ---
color0                #131318
color1                #ffb4ab
color2                #e9b9d3
color3                #c6c4dd
color4                #c1c1ff
color5                #e9b9d3
color6                #c6c4dd
color7                #e4e1e9

color8                #47464f
color9                #93000a
color10               #5f3c51
color11               #454559
color12               #404178
color13               #454559
color14               #5f3c51
color15               #c8c5d0

# --- Starship Prompt Bubbles ---
color255              #404178
color254              #c1c1ff
color253              #454559
color252              #c6c4dd
color251              #5f3c51
color250              #e9b9d3
color249              #93000a
color248              #ffb4ab

color232              #e2dfff
color233              #2a2a60
color234              #e2e0f9
color235              #2f2f42
color236              #ffd8eb
color237              #46263a
color238              #ffdad6
color239              #690005
color240              #e2dfff

# Matched with unthemed light/dark
color243              #c1c1ff
color244              #ffb4ab
color245              #47464f

# --- UI Elements ---
active_tab_foreground   #2a2a60
active_tab_background   #c1c1ff
inactive_tab_foreground #e2dfff
inactive_tab_background #404178

active_border_color     #c1c1ff
inactive_border_color   #918f9a

# --- Marks ---
mark1_foreground        #14134a
mark1_background        #e2dfff
mark2_foreground        #1a1a2c
mark2_background        #e2e0f9
mark3_foreground        #2f1124
mark3_background        #ffd8eb
