# --- Main Colors ---
background            #111318
foreground            #e1e2e9
cursor                #e1e2e9
cursor_text_color     #111318

selection_background  #3c4758
selection_foreground  #d8e3f8

url_color             #d9bde3

# --- ANSI Colors ---
color0                #111318
color1                #ffb4ab
color2                #d9bde3
color3                #bcc7db
color4                #a4c9fe
color5                #d9bde3
color6                #bcc7db
color7                #e1e2e9

color8                #43474e
color9                #93000a
color10               #543f5e
color11               #3c4758
color12               #1f4876
color13               #3c4758
color14               #543f5e
color15               #c3c6cf

# --- Starship Prompt Bubbles ---
color255              #1f4876
color254              #a4c9fe
color253              #3c4758
color252              #bcc7db
color251              #543f5e
color250              #d9bde3
color249              #93000a
color248              #ffb4ab

color232              #d3e3ff
color233              #00315c
color234              #d8e3f8
color235              #263141
color236              #f6d9ff
color237              #3d2946
color238              #ffdad6
color239              #690005
color240              #d3e3ff

# Matched with unthemed light/dark
color243              #a4c9fe
color244              #ffb4ab
color245              #43474e

# --- UI Elements ---
active_tab_foreground   #00315c
active_tab_background   #a4c9fe
inactive_tab_foreground #d3e3ff
inactive_tab_background #1f4876

active_border_color     #a4c9fe
inactive_border_color   #8d9199

# --- Marks ---
mark1_foreground        #001c39
mark1_background        #d3e3ff
mark2_foreground        #111c2b
mark2_background        #d8e3f8
mark3_foreground        #261430
mark3_background        #f6d9ff
