local rule = hl.window_rule

rule ({	match = { class = "kitty"	},	float = true})
rule ({	match = { class = "pcmanfm-qt"	},	float = true})
rule ({	match = { class = "foot"	},	float = true})
rule ({	match = { class = "audacity"	},	float = true})
rule ({	match = { class = "chromium-browser"	},	float = true})
rule ({	match = { class = "FeelUOwn"	},	float = true})
rule ({	match = { class = "org.telegram.desktop"	},	float = true})
rule ({	match = { class = "org.localsend.localsend_app"	},	float = true})
rule ({	match = { class = "org.zathura.Zathura"	},	float = true})
rule ({	match = { class = "nwg-look"	},	float = true})
rule ({	match = { class = "qt6ct"	},	float = true})
rule ({	match = { class = "qt5ct"	},	float = true})
rule ({	match = { class = "kvantummanager"	},	float = true})
rule ({	match = { class = "YACReader"	},	float = true})
rule ({	match = { class = "org.mozilla.Thunderbird"	},	float = true})
rule ({	match = { class = "mpv"	},	float = true})
rule ({	match = { class = "io.githu.mpc_qt.mpc-qt" ,title="Properties"	},	float = true})
rule ({	match = { class = "io.githu.mpc_qt.mpc-qt" ,title="Open File"	},	float = true})
rule ({	match = { class = "io.githu.mpc_qt.mpc-qt" ,title="Options"	},	float = true})
rule ({	match = { class = "lxqt-archiver"	},	float = true})
rule ({	match = { class = "gparted"	},	float = true})
rule ({	match = { class = "org.kde.kwave"	},	float = true})
rule ({	match = { class = "org.fcitx.fcitx-config-qt"	},	float = true})
rule ({	match = { class = "com.github.johnfactotum.Foliate"	},	float = true})
rule ({	match = { class = "org.pwmt.zathura"	},	float = true})
rule ({	match = { class = "venera"	},	float = true})
rule ({	match = { class = "nm-connection-editor"	},	float = true})
rule ({	match = { class = "lxtask"	},	float = true})
rule ({	match = { class = "org.pulseaudio.pavucontrol"	},	float = true})
rule ({	match = { class = "com.github.wwmm.easyeffects"	},	float = true})
rule ({	match = { class = "org.keepassxc.KeePassXC"	},	float = true})
rule ({	match = { class = "org.musicbrainz.Picard"	},	float = true})
rule ({	match = { class = "org.gnome.Nautilus"	},	float = true})
rule ({	match = { class = "app.drey.EarTag"	},	float = true})
rule ({	match = { class = "moe.tsuna.tsukimi"	},	float = true})
rule ({	match = { class = "info.febvre.komikku"	},	float = true})
rule ({	match = { class = "org.gnome.FileRoller"	},	float = true})
rule ({	match = { class = "com.vyp3r.ProtonPlus"	},	float = true})
rule ({	match = { class = "fr.handbrake.ghb"	},	float = true})
rule ({	match = { class = "wechat"	},	float = true})
rule ({	match = { class = "QQ"	},	float = true})
rule ({	match = { class = "fooyin"	},	float = true})
rule ({	match = { class = "resolve", title = "Project Manager"	},	float = true})

--layrule
local layrule = hl.layer_rule
layrule ({ match = {namespace = "rofi" }, ignore_alpha = 0.5, blur = true })
